# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1

orbs:
  ruby: circleci/ruby@1

jobs:
  test:
    parameters:
      ruby-version:
        type: string
    docker:
      - image: "cimg/base:stable"
    working_directory: ~/repo
    steps:
      - checkout
      - ruby/install:
          version: << parameters.ruby-version >>
      - ruby/install-deps:
          key: gems-v1-<< parameters.ruby-version >>
      - ruby/rubocop-check
      - ruby/rspec-test
  publish:
    docker:
      - image: ruby:3.0
    steps:
      - checkout
      - run:
          name: Generate credentials for authenticating with GitHub Packages
          command: |
            mkdir -p ~/.gem
            touch ~/.gem/credentials
            chmod 600 ~/.gem/credentials
            echo ":github: Bearer ${GITHUB_PACKAGES_TOKEN}" >> ~/.gem/credentials
      - run:
          name: Build gem
          command: |
            bundle install
            gem build *.gemspec
      - run:
          name: Publish gem to GitHub Packages
          command: gem push --key github --host https://rubygems.pkg.github.com/healthiqeng ./*.gem

workflows:
  version: 2
  test:
    jobs:
      - test:
          matrix:
            parameters:
              ruby-version: ["2.5", "2.6", "2.7", "3.0"]
          filters:
            tags:
              ignore: /v.*/
  test-and-publish:
    jobs:
      - test:
          matrix:
            parameters:
              ruby-version: ["2.5", "2.6", "2.7", "3.0"]
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
      - publish:
          context: github-packages-publishing
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
